# Generated by Django 5.0.3 on 2024-06-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
