# Generated by Django 5.0.3 on 2024-05-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(default='https://m.media-amazon.com/images/I/81CgtwSII3L._SL1500_.jpg'),
            preserve_default=False,
        ),
    ]
